project:
  type: website

website:
  title: "Bryan Mui"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
        
  page-footer: 
    right: "Bryan Mui 2025"

format:
  html:
    theme: lux
    css: styles.css
    toc: true

execute: 
  freeze: auto

