project:
  type: website

website:
  title: "Bryan Mui"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: lux
    css: styles.css
    toc: true



